eureka:
  client:
    serviceUrl:
      register-with-eureka: false
      fetch-registry: false
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: 'admin-service'
  cloud:
    config:
      enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/realo?serverTimezone=UTC
    username: shop
    password: sugo1111

server:
  port: 8083


